---
title: "Shanghai"
author: "JACKTANSNAKE"
date: "2020/6/25"
output: html_document
---

```{r message = FALSE, Warning = FALSE, echo = FALSE}
library(readxl)
library(readr)
library(tidyverse)
library(ggmap)
library(ggthemes)
library(maps) 
library(openintro)
library(tmaptools)
library(httr)
library(lubridate)
```

```{r}
Facility <- read_excel("../dataset/Facility.xlsx")
Facility_Shanghai <- Facility %>%
  filter(City == "上海") %>%
  mutate(Year_Start = mdy(Year_Start)) %>%
  mutate(Year = year(Year_Start))%>%
  drop_na(Year)
```

```{r}
register_google(key = "AIzaSyBvmJ3i5S_-GuGKeho8YD7ZzBG7lDXI3Go", write = TRUE)
```

```{r message = FALSE, warning = FALSE}
set_config(
  use_proxy(url="127.0.0.1", port=1080, username="JACKTANSNAKE",password="12q12q12q")
)
df <- geocode(Facility_Shanghai$Address)
```

```{r}
Facility_Complete <- cbind(Facility_Shanghai, df)
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
get_location_bbox <- function (place) {
  # Returns a bounding box around a place, such as "United States"
  # suitable for passing to the location parameter of ggmap
  if (tolower(place) == "world") {   # Earth is funny because of the bounds so handle it separately
    bbox <- c(-180, 179, 82.1, -57)
  } else {
    res <- geocode_OSM(place)
    bbox <- c(res$bbox$xmin, res$bbox$xmax, res$bbox$ymax, res$bbox$ymin)
  }
  names(bbox) <- c("left", "right", "top", "bottom")
  return (bbox)
}
```

```{r message = FALSE}
bbox_Shanghai <- c(left = 120.90, bottom = 30.70, right = 121.90, top = 31.90)
map_Shanghai <- get_map(bbox_Shanghai)
```

```{r}
ggmap(map_Shanghai) + 
  geom_point(data = Facility_Complete,
             aes(x = lon, y = lat, color = Class),
             alpha = .5)
```

```{r}
Facility_Complete %>%
  group_by(Class) %>%
  summarise(n = n())
```

```{r}
Facility_Shanghai %>%
  group_by(Year) %>%
  summarise(sum = sum(Bed))
```